version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"

  - package-ecosystem: "npm"
    directory: "/mcp-server"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 5
