#!/usr/bin/env bash
# gen-catalogue.sh — Generates SKILLS.md, a one-page catalogue of every skill
# and its description, read from each SKILL.md frontmatter and Type line.
#
# Usage: bash scripts/gen-catalogue.sh          # write SKILLS.md
#        bash scripts/gen-catalogue.sh --check  # exit 1 if SKILLS.md is stale

set -euo pipefail
export LC_ALL=C

cd "$(dirname "$0")/.."

OUT="SKILLS.md"
CHECK=false
if [[ "${1:-}" == "--check" ]]; then
    CHECK=true
fi

BODY="$(mktemp)"
GENERATED="$(mktemp)"
trap 'rm -f "$BODY" "$GENERATED"' EXIT

# Emits "<name><TAB><table row>" for every skill in one cluster directory.
cluster_rows() {
    local cluster="$1" skill_md name type desc
    for skill_md in "$cluster"/*/SKILL.md; do
        [ -f "$skill_md" ] || continue
        name="$(basename "$(dirname "$skill_md")")"
        desc="$(awk '/^description:/ { sub(/^description: *"?/, ""); sub(/"?$/, ""); print; exit }' "$skill_md")"
        type="$(sed -n 's/^> \*\*Type:\*\* *//p' "$skill_md" | head -1)"
        type="${type:-instructional}"
        desc="${desc//|/\\|}"
        printf "%s\t| \`%s\` | %s | %s |\n" "$name" "$name" "$type" "$desc"
    done
}

for cluster in clusters/*/; do
    cluster="${cluster%/}"
    {
        printf '## %s\n\n' "$(basename "$cluster")"
        printf '| Skill | Type | Description |\n|---|---|---|\n'
        cluster_rows "$cluster" | sort -t$'\t' -k1,1 | cut -f2-
        printf '\n'
    } >> "$BODY"
done

TOTAL="$(grep -c '^| `' "$BODY" || true)"

{
    printf '# Skills catalogue\n\n'
    printf "> Generated by \`scripts/gen-catalogue.sh\`. Do not edit by hand.\n\n"
    cat "$BODY"
    printf 'Total: %s skills\n' "$TOTAL"
} > "$GENERATED"

if $CHECK; then
    if ! cmp -s "$GENERATED" "$OUT"; then
        echo "SKILLS.md is stale: run bash scripts/gen-catalogue.sh"
        exit 1
    fi
    echo "SKILLS.md is current"
    exit 0
fi

cp "$GENERATED" "$OUT"
echo "Wrote $OUT ($TOTAL skills)"
